-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-06-04 21:02:21 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE druzyny (
    nazwa_klubu      VARCHAR2(50) NOT NULL,
    lokalizacja      VARCHAR2(50) NOT NULL,
    stadion          VARCHAR2(50) NOT NULL,
    budzet           NUMBER,
    ilosc_mistrzostw NUMBER,
    data_powstania   DATE
);

ALTER TABLE druzyny ADD CONSTRAINT druzyny_pk PRIMARY KEY ( nazwa_klubu );

CREATE TABLE menadzerowie (
    id_menadzera   NUMBER NOT NULL,
    imie           VARCHAR2(50) NOT NULL,
    nazwisko       VARCHAR2(50) NOT NULL,
    nazwa_panstwa  VARCHAR2(50) NOT NULL,
    kod_kraju      VARCHAR2(5) NOT NULL,
    wyplata        NUMBER,
    id_zawodnika   INTEGER,
    numer_telefonu VARCHAR2(50) NOT NULL
);

ALTER TABLE menadzerowie ADD CONSTRAINT menadzerowie_pk PRIMARY KEY ( id_menadzera );

CREATE TABLE panstwa (
    nazwa_panstwa VARCHAR2(50) NOT NULL,
    kod_kraju     VARCHAR2(5)
);

ALTER TABLE panstwa ADD CONSTRAINT panstwa_pk PRIMARY KEY ( nazwa_panstwa );

CREATE TABLE pracownicy (
    nazwa_klubu     VARCHAR2(50) NOT NULL,
    imie            VARCHAR2(50) NOT NULL,
    nazwisko        VARCHAR2(50) NOT NULL,
    zawod           VARCHAR2(50) NOT NULL,
    wyplata         NUMBER,
    data_dolaczenia DATE NOT NULL,
    obywatelstwo    VARCHAR2(50),
    kod_kraju       VARCHAR2(5),
    id_pracownika   NUMBER NOT NULL
);

ALTER TABLE pracownicy ADD CONSTRAINT pracownicy_pk PRIMARY KEY ( id_pracownika );

CREATE TABLE sedziowie (
    id_sedziego VARCHAR2(5) NOT NULL,
    imie        VARCHAR2(50) NOT NULL,
    nazwisko    VARCHAR2(50) NOT NULL,
    wyplata     NUMBER,
    ocena       NUMBER,
    stadion     VARCHAR2(50) NOT NULL
);

ALTER TABLE sedziowie ADD CONSTRAINT sedziowie_pk PRIMARY KEY ( id_sedziego );

CREATE TABLE sponsorzy (
    nazwa_firmy   VARCHAR2(50) NOT NULL,
    nazwa_klubu   VARCHAR2(50) NOT NULL,
    budzet        NUMBER,
    nazwa_panstwa VARCHAR2(50)
);

ALTER TABLE sponsorzy ADD CONSTRAINT sponsorzy_pk PRIMARY KEY ( nazwa_firmy );

CREATE TABLE stadiony (
    nazwa_stadionu VARCHAR2(50) NOT NULL,
    miasto         VARCHAR2(50) NOT NULL,
    nazwa_klubu    VARCHAR2(50) NOT NULL,
    ilosc_miejsc   INTEGER
);

ALTER TABLE stadiony ADD CONSTRAINT stadiony_pk PRIMARY KEY ( nazwa_stadionu );

CREATE TABLE zawodnicy (
    id_zawodnika   NUMBER NOT NULL,
    imie           VARCHAR2(50) NOT NULL,
    nazwisko       VARCHAR2(50) NOT NULL,
    nazwa_panstwa  VARCHAR2(50) NOT NULL,
    kod_kraju      VARCHAR2(5) NOT NULL,
    wzrost         NUMBER NOT NULL,
    data_ur        DATE NOT NULL,
    nazwa_klubu    VARCHAR2(50) NOT NULL,
    id_menadzera   NUMBER NOT NULL,
    numer_koszulki INTEGER,
    wyplata        NUMBER
);

ALTER TABLE zawodnicy ADD CONSTRAINT zawodnicy_pk PRIMARY KEY ( id_zawodnika );

ALTER TABLE menadzerowie
    ADD CONSTRAINT menadzerowie_panstwa_fk FOREIGN KEY ( nazwa_panstwa )
        REFERENCES panstwa ( nazwa_panstwa );

ALTER TABLE menadzerowie
    ADD CONSTRAINT menadzerowie_panstwa_fkv1 FOREIGN KEY ( kod_kraju )
        REFERENCES panstwa ( nazwa_panstwa );

ALTER TABLE zawodnicy
    ADD CONSTRAINT zawodnicy_druzyny_fk FOREIGN KEY ( nazwa_klubu )
        REFERENCES druzyny ( nazwa_klubu );

ALTER TABLE zawodnicy
    ADD CONSTRAINT zawodnicy_menadzerowie_fk FOREIGN KEY ( id_menadzera )
        REFERENCES menadzerowie ( id_menadzera );

ALTER TABLE zawodnicy
    ADD CONSTRAINT zawodnicy_panstwa_fk FOREIGN KEY ( nazwa_panstwa )
        REFERENCES panstwa ( nazwa_panstwa );

ALTER TABLE zawodnicy
    ADD CONSTRAINT zawodnicy_panstwa_fkv1 FOREIGN KEY ( kod_kraju )
        REFERENCES panstwa ( nazwa_panstwa );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
